from django.db import models
import uuid
import random
import string


def generate_task_code():
    """Generate a unique, human-readable task code like VNH-A3X9K."""
    suffix = ''.join(random.choices(string.ascii_uppercase + string.digits, k=5))
    return f"VNH-{suffix}"


class Task(models.Model):
    """Core task record created from a customer request."""

    INTENT_CHOICES = [
        ('send_money', 'Send Money'),
        ('hire_service', 'Hire Service'),
        ('verify_document', 'Verify Document'),
        ('get_airport_transfer', 'Airport Transfer'),
        ('check_status', 'Check Status'),
        ('unknown', 'Unknown'),
    ]

    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('cancelled', 'Cancelled'),
    ]

    RISK_LEVEL_CHOICES = [
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
    ]

    TEAM_CHOICES = [
        ('Finance', 'Finance Team'),
        ('Operations', 'Operations Team'),
        ('Legal', 'Legal Team'),
        ('Support', 'Support Team'),
    ]

    # Identifiers
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    task_code = models.CharField(max_length=20, unique=True, default=generate_task_code)

    # Core fields
    original_request = models.TextField(help_text="The raw text the customer submitted")
    intent = models.CharField(max_length=50, choices=INTENT_CHOICES, default='unknown')
    entities = models.JSONField(default=dict, help_text="Extracted entities as JSON")

    # Risk
    risk_score = models.IntegerField(default=0, help_text="Risk score 0-100")
    risk_level = models.CharField(max_length=10, choices=RISK_LEVEL_CHOICES, default='low')
    risk_reasons = models.JSONField(default=list, help_text="List of reasons contributing to risk")

    # Assignment & status
    assigned_team = models.CharField(max_length=50, choices=TEAM_CHOICES, default='Support')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.task_code} — {self.intent} ({self.status})"

    def save(self, *args, **kwargs):
        # Auto-set risk level from score
        if self.risk_score >= 70:
            self.risk_level = 'high'
        elif self.risk_score >= 40:
            self.risk_level = 'medium'
        else:
            self.risk_level = 'low'
        super().save(*args, **kwargs)


class TaskStep(models.Model):
    """Ordered fulfilment steps generated by AI for a task."""
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='steps')
    step_number = models.PositiveIntegerField()
    title = models.CharField(max_length=200)
    description = models.TextField()
    is_complete = models.BooleanField(default=False)

    class Meta:
        ordering = ['step_number']

    def __str__(self):
        return f"Step {self.step_number}: {self.title}"


class TaskMessage(models.Model):
    """The three confirmation messages (WhatsApp, Email, SMS) for a task."""
    CHANNEL_CHOICES = [
        ('whatsapp', 'WhatsApp'),
        ('email', 'Email'),
        ('sms', 'SMS'),
    ]

    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='messages')
    channel = models.CharField(max_length=20, choices=CHANNEL_CHOICES)
    subject = models.CharField(max_length=300, blank=True, help_text="Email subject line only")
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['channel']

    def __str__(self):
        return f"{self.channel.upper()} message for {self.task.task_code}"


class StatusHistory(models.Model):
    """Audit trail — every time a task's status changes."""
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='status_history')
    old_status = models.CharField(max_length=20)
    new_status = models.CharField(max_length=20)
    changed_at = models.DateTimeField(auto_now_add=True)
    note = models.CharField(max_length=300, blank=True)

    class Meta:
        ordering = ['-changed_at']

    def __str__(self):
        return f"{self.task.task_code}: {self.old_status} → {self.new_status}"
