# Generated by Django 4.2.11 on 2026-04-16 16:23

from django.db import migrations, models
import django.db.models.deletion
import tasks.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_code', models.CharField(default=tasks.models.generate_task_code, max_length=20, unique=True)),
                ('original_request', models.TextField(help_text='The raw text the customer submitted')),
                ('intent', models.CharField(choices=[('send_money', 'Send Money'), ('hire_service', 'Hire Service'), ('verify_document', 'Verify Document'), ('get_airport_transfer', 'Airport Transfer'), ('check_status', 'Check Status'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('entities', models.JSONField(default=dict, help_text='Extracted entities as JSON')),
                ('risk_score', models.IntegerField(default=0, help_text='Risk score 0-100')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('risk_reasons', models.JSONField(default=list, help_text='List of reasons contributing to risk')),
                ('assigned_team', models.CharField(choices=[('Finance', 'Finance Team'), ('Operations', 'Operations Team'), ('Legal', 'Legal Team'), ('Support', 'Support Team')], default='Support', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_complete', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tasks.task')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='TaskMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Email subject line only', max_length=300)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tasks.task')),
            ],
            options={
                'ordering': ['channel'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tasks.task')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
